cleanup init-setup-app

diff --git a/root/etc/s6-overlay/s6-rc.d/init-setup-app/run b/root/etc/s6-overlay/s6-rc.d/init-setup-app/run
--- a/root/etc/s6-overlay/s6-rc.d/init-setup-app/run
+++ b/root/etc/s6-overlay/s6-rc.d/init-setup-app/run
@@ -1,15 +1,12 @@
 #!/command/with-contenv bash
 # shellcheck shell=bash
 
-umask "${UMASK}"
+# shellcheck source=/dev/null
+source /etc/s6-overlay/scripts/bash-functions
 
-mask() {
-    local n=3
-    [[ ${#1} -le 5 ]] && n=$(( ${#1} - 3 ))
-    local a="${1:0:${#1}-n}"
-    local b="${1:${#1}-n}"
-    printf "%s%s\n" "${a//?/*}" "$b"
-}
+set -e
+
+umask "${UMASK}"
 
 echo "
 ----------------------------------------------------------------------
@@ -24,12 +21,16 @@ PLEX_PURGE_CODECS=${PLEX_PURGE_CODECS}
 ----------------------------------------------------------------------
 "
 
-echo "Applying permissions to /transcode"
-chmod "=rwx" "/transcode"
-find "/transcode" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
+if [[ ! -d "${CONFIG_DIR}/Temp" ]]; then
+    log_inf "Creating directory [${CONFIG_DIR}/Temp]."
+    mkdir "${CONFIG_DIR}/Temp"
+    find "${CONFIG_DIR}/Temp" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
+fi
 
-############
-## Functions
+#################
+## Configure Plex
+prefFile="${CONFIG_DIR}/Preferences.xml"
+
 function getPref {
     local key="$1"
     xmlstarlet sel -T -t -m "/Preferences" -v "@${key}" -n "${prefFile}"
@@ -45,15 +46,12 @@ function setPref {
     else
         xmlstarlet ed --inplace --insert "/Preferences"  --type attr -n "${key}" -v "${value}" "${prefFile}"
     fi
+    log_inf "Set preference [${key}] to [${value}]."
 }
-
-#################
-## Configure Plex
-prefFile="${CONFIG_DIR}/Preferences.xml"
 
 # Create empty Preferences.xml file if it doesn't exist already
 if [[ ! -f "${prefFile}" ]]; then
-    echo "Creating empty Preferences.xml..."
+    log_inf "Creating empty [Preferences.xml] file."
     cat > "${prefFile}" <<-EOF
 <?xml version="1.0" encoding="utf-8"?>
 <Preferences/>
@@ -61,22 +59,37 @@ EOF
     find "${prefFile}" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
 fi
 
-# Setup Server's client identifier
-serial="$(getPref "MachineIdentifier")"
-if [[ -z "${serial}" ]]; then
+# Set MachineIdentifier
+if [[ -z "$(getPref "MachineIdentifier")" ]]; then
     serial="$(cat /proc/sys/kernel/random/uuid)"
     setPref "MachineIdentifier" "${serial}"
 fi
-clientId="$(getPref "ProcessedMachineIdentifier")"
-if [[ -z "${clientId}" ]]; then
+
+# Set ProcessedMachineIdentifier
+if [[ -z "$(getPref "ProcessedMachineIdentifier")" ]]; then
     clientId="$(echo -n "${serial}- Plex Media Server" | sha1sum | cut -b 1-40)"
     setPref "ProcessedMachineIdentifier" "${clientId}"
 fi
 
-# Get server token and only turn claim token into server token if we have former but not latter.
-token="$(getPref "PlexOnlineToken")"
-if [[ -n "${PLEX_CLAIM_TOKEN}" ]] && [[ -z "${token}" ]]; then
-    echo "Attempting to obtain server token from claim token..."
+# Set customConnections
+if [[ -n "${PLEX_ADVERTISE_URL}" ]]; then
+    setPref "customConnections" "${PLEX_ADVERTISE_URL}"
+fi
+
+# Set allowedNetworks
+if [[ -n "${PLEX_NO_AUTH_NETWORKS}" ]]; then
+    setPref "allowedNetworks" "${PLEX_NO_AUTH_NETWORKS}"
+fi
+
+# Set TranscoderTempDirectory
+if [[ -z "$(getPref "TranscoderTempDirectory")" ]]; then
+    setPref "TranscoderTempDirectory" "${CONFIG_DIR}/Temp"
+fi
+
+# Set PlexOnlineToken
+clientId="$(getPref "ProcessedMachineIdentifier")"
+if [[ -n "${PLEX_CLAIM_TOKEN}" ]] && [[ -z "$(getPref "PlexOnlineToken")" ]]; then
+    log_inf "Attempting to obtain server token from claim token..."
     loginInfo="$(curl -fsSL -X POST \
         -H 'X-Plex-Client-Identifier: '"${clientId}" \
         -H 'X-Plex-Product: Plex Media Server'\
@@ -88,87 +101,39 @@ if [[ -n "${PLEX_CLAIM_TOKEN}" ]] && [[ -z "${token}" ]]; then
         -H 'X-Plex-Device: Linux' \
         "https://plex.tv/api/claim/exchange?token=${PLEX_CLAIM_TOKEN}")"
     token="$(echo "$loginInfo" | sed -n 's/.*<authentication-token>\(.*\)<\/authentication-token>.*/\1/p')"
-
-    if [[ "$token" ]]; then
-        echo "Token obtained successfully!"
+    if [[ -n "$token" ]]; then
         setPref "PlexOnlineToken" "${token}"
     fi
 fi
 
-# Set other preferences
-[[ -n "${ADVERTISE_IP}" ]] && PLEX_ADVERTISE_URL=${ADVERTISE_IP}
-if [[ -n "${PLEX_ADVERTISE_URL}" ]]; then
-    echo "Setting customConnections to: ${PLEX_ADVERTISE_URL}"
-    setPref "customConnections" "${PLEX_ADVERTISE_URL}"
-fi
-
-[[ -n "${ALLOWED_NETWORKS}" ]] && PLEX_NO_AUTH_NETWORKS=${ALLOWED_NETWORKS}
-if [[ -n "${PLEX_NO_AUTH_NETWORKS}" ]]; then
-    echo "Setting allowedNetworks to: ${PLEX_NO_AUTH_NETWORKS}"
-    setPref "allowedNetworks" "${PLEX_NO_AUTH_NETWORKS}"
-fi
-
-# Set transcoder directory if not yet set
-if [[ -z "$(getPref "TranscoderTempDirectory")" ]]; then
-    echo "Setting TranscoderTempDirectory to: /transcode"
-    setPref "TranscoderTempDirectory" "/transcode"
-fi
-
-# Remove pid file
-rm -f "${CONFIG_DIR}/plexmediaserver.pid"
-
-#############
-## HW Support
-DEVICES=$(find /dev/dri /dev/dvb -type c -print 2>/dev/null)
-
-for i in ${DEVICES}; do
-    # Get the group ID and NAME (if exists) for the current device in the list
-    DEVICE_GROUP_ID=$(stat -c '%g' "$i")
-    DEVICE_GROUP_NAME=$(getent group "${DEVICE_GROUP_ID}" | awk -F: '{print $1}')
-
-    # If group NAME doesn't exist, create it and assign it the group ID
-    if [[ -z "${DEVICE_GROUP_NAME}" ]]; then
-        DEVICE_GROUP_NAME="video${RANDOM}"
-        groupadd -g "${DEVICE_GROUP_ID}" "${DEVICE_GROUP_NAME}"
-    fi
-
-    # If the user hotio isn't a member of the group, add him
-    getent group "${DEVICE_GROUP_NAME}" | grep -q hotio || usermod -a -G "${DEVICE_GROUP_NAME}" hotio
-done
-
 ######################
 ## Purge Codecs folder
 if [[ "${PLEX_PURGE_CODECS}" == "true" ]]; then
-    echo "Purging Codecs folder..."
+    log_inf "Purging folder [${CONFIG_DIR}/Codecs]..."
     find "${CONFIG_DIR}/Codecs" -mindepth 1 -not -name '.device-id' -print -delete
 fi
 
 ####################
 ## Install Plex Beta
 if [[ "${PLEX_BETA_INSTALL}" == "true" ]]; then
-    echo "Attempting beta installation..."
+    log_inf "Attempting beta installation..."
     do_install=true
-
     token="$(getPref "PlexOnlineToken")"
     if [[ -z "${token}" ]]; then
-        echo "No token has been found! Aborting installation."
+        log_wrn "No token has been found! Aborting installation."
         do_install=false
     fi
-
     PLEX_PASS_VERSION=$(curl -fsSL "https://plex.tv/api/downloads/5.json?channel=plexpass&X-Plex-Token=${token}" | jq -r .computer.Linux.version)
     PUBLIC_VERSION=$(curl -fsSL "https://plex.tv/api/downloads/5.json" | jq -r .computer.Linux.version)
-
     if [[ "${PUBLIC_VERSION}" == "${PLEX_PASS_VERSION}" ]] && [[ "${do_install}" == true ]]; then
-        echo "No eligable beta found! Aborting installation."
+        log_inf "No eligable beta for installation has been found."
         do_install=false
     fi
-
     INSTALLED_VERSION=$(cat "${APP_DIR}/version")
     if [[ "${INSTALLED_VERSION}" == "${PLEX_PASS_VERSION}" ]] && [[ "${do_install}" == true ]]; then
-        echo "Already on the latest beta \"${PLEX_PASS_VERSION}\", no update required. Aborting installation."
+        log_inf "Already on the latest beta [${PLEX_PASS_VERSION}], no update required."
         do_install=false
     fi
-
     if [[ "${do_install}" == true ]]; then
         case "${BUILD_ARCHITECTURE}" in
             linux-amd64)
@@ -178,7 +143,6 @@ if [[ "${PLEX_BETA_INSTALL}" == "true" ]]; then
                 architecture="arm64"
                 ;;
         esac
-
         debfile="/tmp/plex.deb" && \
             curl -fsSL "https://downloads.plex.tv/plex-media-server-new/${PLEX_PASS_VERSION}/debian/plexmediaserver_${PLEX_PASS_VERSION}_${architecture}.deb" -o "${debfile}" && \
             rm -rf "${APP_DIR:?}/bin" && \
@@ -188,10 +152,10 @@ if [[ "${PLEX_BETA_INSTALL}" == "true" ]]; then
             echo "${PLEX_PASS_VERSION}" > "${APP_DIR}/version" && \
             INSTALL_OK="yes"
         if [[ "${INSTALL_OK}" != "yes" ]]; then
-            echo -e '\e[31m'"Installation of beta \"${PLEX_PASS_VERSION}\" failed!"'\e[0m'
+            log_err "Installation of beta [${PLEX_PASS_VERSION}] failed! Exiting..."
             exit 1
         else
-            echo "Installation of beta \"${PLEX_PASS_VERSION}\" succeeded."
+            log_inf "Installation of beta [${PLEX_PASS_VERSION}] succeeded."
         fi
     fi
 fi
@@ -199,10 +163,8 @@ fi
 ######################
 ## Install Plex Custom
 INSTALLED_VERSION=$(cat "${APP_DIR}/version")
-
 if [[ "${PLEX_BETA_INSTALL}" == "http"* ]] && [[ "${PLEX_BETA_INSTALL}" != "${INSTALLED_VERSION}" ]]; then
-    echo "Attempting custom installation...don't come crying for support!"
-
+    log_wrn "Attempting custom installation..."
     debfile="/tmp/plex.deb" && \
         curl -fsSL "${PLEX_BETA_INSTALL}" -o "${debfile}" && \
         rm -rf "${APP_DIR:?}/bin" && \
@@ -212,9 +174,9 @@ if [[ "${PLEX_BETA_INSTALL}" == "http"* ]] && [[ "${PLEX_BETA_INSTALL}" != "${IN
         echo "${PLEX_BETA_INSTALL}" > "${APP_DIR}/version" && \
         INSTALL_OK="yes"
     if [[ "${INSTALL_OK}" != "yes" ]]; then
-        echo -e '\e[31m'"Installation of \"${PLEX_BETA_INSTALL}\" failed!"'\e[0m'
+        log_err "Installation of beta [${PLEX_PASS_VERSION}] failed! Exiting..."
         exit 1
     else
-        echo "Installation of \"${PLEX_BETA_INSTALL}\" succeeded."
+        log_inf "Installation of beta [${PLEX_PASS_VERSION}] succeeded."
     fi
 fi
